# .air.toml
root = "."
tmp_dir = "tmp"
[build]
  cmd = "go build cmd/app -o ./tmp/main.exe ."
  bin = "./tmp/main.exe"
  delay = 1000 # ms
  exclude_dir = ["assets", "tmp", "vendor"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_regex = ["_test\\.go"]